require "src.engine.scene.handler"
require "raylib"

global Window = @record{
	scene_handler: SceneHandler,
}

function Window:init(width: usize, height: usize, title: string): void
	rl.initAudioDevice()
	rl.initWindow(width, height, title)
end

function Window:run(): void
	while rl.windowShouldClose() ~= true do
		self.scene_handler:update_all()
		rl.beginDrawing()
		rl.clearBackground(rl.BLACK)
		self.scene_handler:render_all()
		rl.drawFPS(0, 0)
		rl.endDrawing()
	end
end