require "src.engine.audio.syncedplayer"
require "src.game.global"

global SingleplayerScene = @record{
    audio: SyncedAudioPlayer,
    initialized: boolean,
}

function SingleplayerScene:init(): void
    self.audio = SyncedAudioPlayer.from_bytes(DemoMap.audio, 0.1, 1.0)
    self.audio:play(0.0)
end

function SingleplayerScene:update(dt: float32): State
    self.audio:update()
    return State.Singleplayer
end

function SingleplayerScene:render(): void
end
